name: flight_area_exporter
description: map capture and save as flight area image file.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.8+48

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  universal_platform: ^1.0.0+1
  universal_html: ^2.2.4
  device_info_plus: ^9.0.3
  package_info_plus: ^4.1.0
  quiver: ^3.2.1
  email_validator: ^2.1.17
  logger: ^2.0.2
  go_router: ^10.1.2
  flutter_dotenv: ^5.1.0
  pwa_update_listener: ^0.1.0
  file_selector: ^1.0.1
  flutter_screenutil: ^5.9.0
  screenshot: ^2.1.0
  xml: ^6.3.0
  flutter_colorpicker: ^1.0.3

  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.5.0
  gap: ^3.0.1
  flutter_native_splash: ^2.3.2

  # firebase
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.9.0
  firebase_storage: ^11.2.6
  google_sign_in: ^6.1.5

  # riverpod
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # map
  flutter_map: ^6.0.0-dev.2
  latlong2: ^0.9.0
  flutter_map_line_editor: ^5.0.0

dependency_overrides:
    flutter_map:
        git:
            url: https://github.com/fleaflet/flutter_map.git
            # ref: main (custom branch/commit)

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  source_gen: ^1.4.0

  riverpod_generator: ^2.3.2
  freezed: ^2.4.2
  json_serializable: ^6.7.1

  flutter_lints: ^2.0.3
  import_sorter: ^4.6.0
  pedantic_mono: ^1.24.0+1

flutter:
  uses-material-design: true

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP/NotoSansJP-Bold.otf
          weight: 700
        - asset: assets/fonts/NotoSansJP/NotoSansJP-Regular.otf
          weight: 400

  assets:
    - assets/
